// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://rgubzbijtldiwdqreptj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndWJ6YmlqdGxkaXdkcXJlcHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0MjIwNjYsImV4cCI6MjA5Mjk5ODA2Nn0._l5dgb1nSslwCducNg8kqI_CjneMlNPVzJQ6ZdZtDT8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);